services:

  # ─── MÓDULO 03: CPU ───────────────────────────────────────────
  cpu-db:
    image: postgres:17-alpine
    container_name: cpu-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gj28752317
      POSTGRES_DB: ms_cpu
    ports:
      - '5433:5432'
    volumes:
      - cpu_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - cpu-net

  cpu-backend:
    build:
      context: ./sistemas-operativos-xD
      dockerfile: Dockerfile
    container_name: cpu-backend
    ports:
      - '3003:3003'
    environment:
      - NODE_ENV=production
      - PORT=3003
      - DB_HOST=cpu-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=gj28752317
      - DB_NAME=ms_cpu
    depends_on:
      - cpu-db
    restart: unless-stopped
    networks:
      - cpu-net

  cpu-frontend:
    image: nginx:alpine
    container_name: cpu-frontend
    ports:
      - '8081:80'
    volumes:
      - ./sistemas-operativos-xD/index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - cpu-backend
    restart: unless-stopped
    networks:
      - cpu-net

  # ─── MÓDULO 04: INTERRUPCIONES ────────────────────────────────
  interruptions-backend:
    build:
      context: "./backend S1"
      dockerfile: Dockerfile
    container_name: interruptions-backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - interruptions-net

  interruptions-frontend:
    image: nginx:alpine
    container_name: interruptions-frontend
    ports:
      - '8080:80'
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - interruptions-backend
    restart: unless-stopped
    networks:
      - interruptions-net

volumes:
  cpu_db_data:

networks:
  cpu-net:
  interruptions-net: